#' Perfome principal component analysis.
#'
#'
#' @importFrom methods as new
#'
#' @description
#' Returns a structured object containing the results of the 
#' principal component analysis (PCA) and the cumulative variance.
#'
#' The `DimReductionlist` class generated by this function can be passed to 
#' the `MeCall.Plot()` function to create a scree plot or PCA plot of 
#' the data using the selected principal components. 
#'
#' In addition, it can be passed to the `MeCall.MakeModelMatrix()` function 
#' to include principal components as covariates before conducting a 
#' differential methylation analysis.
#'
#' @param meth A matrix of methylation level.
#'
#' @return "DimReductionlist" S4 class object consisted of :
#' \itemize{Components} {The rotated data according to the `rotation`. The column names represent the principal component names, while the row names represent the samples.}
#' \itemize{cum.var} {The cumulative information explained by each principal component across the entire dataset.}
#' \itemize{sdev} {the square roots of the eigenvalues of the covariance/correlation matrix}
#' \itemize{rotation} {A matrix containing the principal components that represent the eigenvectors.}
#' \itemize{center} {A logical value indicating whether the data has been zero-centered.}
#' \itemize{scale} {A logical value indicating whether the variance of the variables has been scaled to have unit variance.}
#' see [stats::prcomp()] for detail
#'
#' @author Hyun-Ho Yang
#'
#' @seealso [MeCall.Plot()], [MeCall.MakeModelMatrix()]
#'
#' @examples
#' \dontrun{
#' # Run PCA.
#' data.PCA <- MeCall.PCA(meth = data.CellComp)
#' }
#'
#' @export
MeCall.PCA <- function(meth = mycellcomp){
message("\n[MeCall]-[notice] : Principal component analysis start.")
if(!is.null(data)){
t_data <- t(data)
data.pca <- prcomp(t_data,scale=FALSE)
message("\n[MeCall]-[notice] : Principal component analysis done.")
Ob <- Set.DimReductionlist(data.pca)
return(Ob)
} else {stop("\n[MeCall]-!!ERROR!! : There is no beta value table in your input variable.")}
}
